# Generated by Django 5.1.15 on 2026-04-18 22:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_type', models.CharField(choices=[('hypar_bridge_export', 'Hypar Bridge Export'), ('knowledge_ingestion', 'Knowledge Ingestion')], max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('retrying', 'Retrying'), ('clarification_required', 'Clarification Required'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('timed_out', 'Timed Out')], default='queued', max_length=40)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('artifact_path', models.CharField(blank=True, default='', max_length=500)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('timeout_seconds', models.PositiveIntegerField(default=120)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_jobs', to='design.designsession')),
            ],
            options={
                'verbose_name': 'Operation Job',
                'verbose_name_plural': 'Operation Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
