"""Utilities for generating Hypar import bridge artifacts.

This module creates spreadsheet-like CSV files from generated layout zones so
workspaces without direct API credentials can still upload planning results.
"""

from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List


DEFAULT_TARGET_AREA_SQM = {
    "living_room": 24.0,
    "kitchen": 12.0,
    "dining": 12.0,
    "bedroom": 14.0,
    "bathroom": 5.0,
    "staircase": 10.0,
    "parking": 15.0,
    "puja_room": 4.0,
    "balcony": 4.0,
    "circulation": 8.0,
    "multi_use": 10.0,
}


def _normalize_room_type(room_type: str) -> str:
    room = str(room_type or "").strip().lower()
    if "bed" in room:
        return "bedroom"
    if "bath" in room or "toilet" in room or "wash" in room:
        return "bathroom"
    return room or "space"


def _room_label(room_type: str) -> str:
    return str(room_type).replace("_", " ").strip().title()


def _default_target_area(room_type: str) -> float:
    return float(DEFAULT_TARGET_AREA_SQM.get(room_type, 10.0))


def _collect_room_counts(parsed_input: Dict[str, object], layout_zones: List[dict]) -> Counter:
    requested_rooms = parsed_input.get("rooms") if isinstance(parsed_input, dict) else []
    normalized_rooms = [
        _normalize_room_type(str(room))
        for room in (requested_rooms or [])
        if str(room).strip()
    ]

    if normalized_rooms:
        counts = Counter(normalized_rooms)
    else:
        counts = Counter(
            _normalize_room_type(str(zone.get("room_type", "")))
            for zone in layout_zones
            if str(zone.get("room_type", "")).strip()
        )

    preferences = parsed_input.get("preferences", {}) if isinstance(parsed_input, dict) else {}
    if isinstance(preferences, dict):
        if preferences.get("parking") and counts.get("parking", 0) == 0:
            counts["parking"] = 1
        if preferences.get("puja_room") and counts.get("puja_room", 0) == 0:
            counts["puja_room"] = 1

    return counts


def _collect_layout_areas(layout_zones: List[dict]) -> Dict[str, float]:
    area_by_room: Dict[str, float] = defaultdict(float)
    for zone in layout_zones:
        room = _normalize_room_type(str(zone.get("room_type", "")))
        width = float(zone.get("width_m", 0.0) or 0.0)
        depth = float(zone.get("depth_m", 0.0) or 0.0)
        area_by_room[room] += max(0.0, width * depth)
    return dict(area_by_room)


def write_hypar_requirements_csv(
    *,
    parsed_input: Dict[str, object],
    layout_zones: List[dict],
    outputs_dir: Path,
    session_seed: str,
    region_id: str,
    building_type: str,
) -> str:
    outputs_dir.mkdir(parents=True, exist_ok=True)
    filename = f"hypar_requirements_{session_seed}.csv"
    target_path = outputs_dir / filename

    counts = _collect_room_counts(parsed_input, layout_zones)
    area_by_room = _collect_layout_areas(layout_zones)

    fieldnames = [
        "space_type",
        "space_name",
        "quantity",
        "target_area_sqm",
        "min_area_sqm",
        "max_area_sqm",
        "priority",
        "department",
        "notes",
        "region_id",
        "building_type",
    ]

    with target_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()

        for room_type in sorted(counts.keys()):
            quantity = max(1, int(counts[room_type]))
            total_area = float(area_by_room.get(room_type, 0.0))
            if total_area <= 0.0:
                target_area = _default_target_area(room_type)
            else:
                target_area = total_area / quantity

            writer.writerow(
                {
                    "space_type": room_type,
                    "space_name": _room_label(room_type),
                    "quantity": quantity,
                    "target_area_sqm": round(target_area, 2),
                    "min_area_sqm": round(target_area * 0.85, 2),
                    "max_area_sqm": round(target_area * 1.15, 2),
                    "priority": "high" if room_type in {"living_room", "kitchen", "bedroom"} else "medium",
                    "department": "Residential Program",
                    "notes": "Generated by Archi3D requirements bridge for Hypar spreadsheet upload.",
                    "region_id": region_id,
                    "building_type": building_type,
                }
            )

    return filename


def write_hypar_bridge_csv(
    *,
    layout_zones: List[dict],
    outputs_dir: Path,
    session_seed: str,
    region_id: str,
    building_type: str,
    parsed_input: Dict[str, object] | None = None,
) -> str:
    outputs_dir.mkdir(parents=True, exist_ok=True)
    filename = f"hypar_bridge_{session_seed}.csv"
    target_path = outputs_dir / filename

    fieldnames = [
        "zone_id",
        "room_type",
        "floor",
        "x_m",
        "y_m",
        "width_m",
        "depth_m",
        "area_sqm",
        "orientation",
        "plot_width_m",
        "plot_depth_m",
        "plot_area_sqm",
        "region_id",
        "building_type",
    ]

    parsed = parsed_input or {}
    plot_width_m = float(parsed.get("plot_width_m", 0.0) or 0.0)
    plot_depth_m = float(parsed.get("plot_depth_m", 0.0) or 0.0)
    plot_area_sqm = round(plot_width_m * plot_depth_m, 3)

    with target_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()

        for zone in layout_zones:
            width_m = float(zone.get("width_m", 0.0))
            depth_m = float(zone.get("depth_m", 0.0))
            writer.writerow(
                {
                    "zone_id": str(zone.get("id", "")),
                    "room_type": str(zone.get("room_type", "")),
                    "floor": int(zone.get("floor", 0)),
                    "x_m": round(float(zone.get("x", 0.0)), 3),
                    "y_m": round(float(zone.get("y", 0.0)), 3),
                    "width_m": round(width_m, 3),
                    "depth_m": round(depth_m, 3),
                    "area_sqm": round(width_m * depth_m, 3),
                    "orientation": str(zone.get("orientation", "")),
                    "plot_width_m": round(plot_width_m, 3),
                    "plot_depth_m": round(plot_depth_m, 3),
                    "plot_area_sqm": plot_area_sqm,
                    "region_id": region_id,
                    "building_type": building_type,
                }
            )

    return filename


def build_hypar_bridge_summary(
    *,
    layout_zones: List[dict],
    artifact_path: str,
    requirements_artifact_path: str,
    region_id: str,
    building_type: str,
) -> Dict[str, object]:
    return {
        "mode": "spreadsheet_upload",
        "artifact_path": artifact_path,
        "requirements_artifact_path": requirements_artifact_path,
        "zone_count": len(layout_zones),
        "region_id": region_id,
        "building_type": building_type,
        "next_step": "Upload the requirements CSV in Hypar via 'Upload a spreadsheet'.",
    }
